version: "2"
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  node:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - redis
    volumes:
      - .:/usr/src/app
